### PR TITLE
App actions

### PR DESCRIPTION
**Pull request by Psycojoker**
Admin UI for the actions. It reuse the mechanisms of the installation form to be generic (this also open the path of doing this for apps remove/upgrade/others).

Nearly absolutely no work as been done on the UI part, it reuses app install form.

Obligatory screenshot:

2018-07-02-122720_1205x926_scrot

I think it's more important to make that available to app devs to gather their feedback that to work on other things for now.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Just to add an interesting tip, we can see on the screenshot `/ Application / Wallabag / app_action`, however, to have access to this page, you have to add `/actions` to the path of the app in the admin panel.
Like that: `domain.tld/yunohost/admin/#/apps/APP/actions`

**Comment by Psycojoker** [comment]
Indeed, sorry for the bad documentation >.>

**Comment by maniackcrudelis** [comment]
No worries, it's an experimental feature. We'll fixing this small things by the time.
Also, by using it in my own packages, I expect to draw a first way to use those features. With that, it would be easier to write a documentation.

**Comment by Psycojoker** [comment]
Yes, don't hesitate to write feedback somewhere (an issue, a pad, whatever we don't lose) and don't hesitate to ask questions :)

**Pull request merged**
