### PR TITLE
Remove appslist management from webadmin

### PR DESCRIPTION
**Pull request by alexAubin**
## Problem

c.f. https://github.com/YunoHost/issues/issues/1302, and also : 

+ as a consequence of https://github.com/YunoHost/yunohost/pull/666, community apps will now be available by default, so the whole advertisement about the community will be outdated

+ the internet cube project stopped using a custom list

To me there is no point anymore to have this feature shown in the admin panel. Maybe it's a good thing to keep it in the CLI for advanced users willing to use custom lists, but otherwise #fuckit 

## Solution

Remove appslist management from the webadmin

## Status

Tested and working

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
But what about the non free list ? Or other apps lists users could want to add ?
Wouldn't be better to modify the message about the tool, and make it clearer ? And also check that it's indeed a correct json file the user is trying to add ?

**Comment by alexAubin** [comment]
Idk, to me those user should just add it through the command line ... One could argue that adding an extra app list which is not maintained by trustable people like us ;) is sort of a security risk because people maintaining the list could override our apps and/or advertise broken apps as level 7+ ...

Anyway what really motivates me is to have seen so many case where people end up adding apps as appslist which broke everything... Even though that should be fixed now, I'm guessing that this whole application list thing confuses users who end up in this page thinking it might be useful, but in fact currently the only reason to go there is to add the community list...

I'm not 100% opposed to keeping it, but it really looks to me like something we don't need and I'm kinda sick of seeing people doing random unexpected stuff with this page and explaining them that this wasn't what they were looking for and/or how to repair stuff

**Comment by maniackcrudelis** [comment]
Saw those users too.
But I feel like removing that would be in opposition with what we were saying about adding a list for non free apps.
I would be more in favor of explaining the tools and restrict what can be added by it.
But actually, I don't use that tool myself...

**Comment by alexAubin** [comment]
Sooooo what about moving that menu in category 'tools' :s

**Comment by alexAubin** [comment]
Closing because superseded by https://github.com/YunoHost/yunohost-admin/pull/248

**Pull request closed without merging**
