### PR TITLE
[enh] Variable assignment code cleanup.

### PR DESCRIPTION
**Pull request by opi**
WIP. Please do not merge right now.

### CODE REVIEW

**Comment by alexAubin** [comment]
Any news on this ? Sounds to me like it's mergeable

**Comment by opi** [comment]
I guess so, but I hoped that *at least* someone else (= other than me) has tried this PR

**Comment by alexAubin** [comment]
Well I gave it a quick try and it seems to work .. not sure I want to check every piece of code specifically just for very minor changes :stuck_out_tongue: 

I think we can just merge this if people are okay with it.

**Comment by opi** [comment]
> not sure I want to check every piece of code

for explicit errors like syntax error, JS should have crashed globally, so you're good

**Pull request merged**
