### PR TITLE
[fix] Remove port when both connection will be closed

### PR DESCRIPTION
**Pull request by eldertek**
Hello, in the past when closing e.g : "port 8080 - tcp - ipv4" when "port - tcp - 8080 - ipv6" is already close, the port stay in firewall, this pr will allows the port to be removed from entry of the firewall webadmin tool.

### CODE REVIEW

**Comment by eldertek** [comment]
Sorry did a bad explanation 
when port 1000 is opened in tcp and closed in udp, and when user closes the tcp, port 1000 remain in webadmin with the fields udp and tcp grayed out

my pr allows to completely close the port when ether udp or tcp is already closed

**Comment by eldertek** [comment]
Someone ?

**Comment by eldertek** [comment]
@alexAubin

**Comment by alexAubin** [comment]
Yes, we've seen your PR
- I'm not the only maintainer in YunoHost, no need to ping me personally
- There's always literally thousands of tasks in YunoHost
- People tend to have a life beside YunoHost

Your PR will be merged when somebody will have the time and energy to properly review it

**Pull request closed without merging**
