### PR TITLE
Add help blocks to admin interface

### PR DESCRIPTION
**Pull request by e-lie**

### CODE REVIEW

**Comment by opi** [comment]
Not sure I want to merge something with `<p>Lorem ipsum dolorem trolololo ut</p>` in ...

**Comment by Kloadut** [comment]
+1

This is more of a WIP pull request, the concept is just to integrate a way to display help in a nice way on the Admin interface

**Comment by opi** [comment]
that's why git branches are for ;)

**Comment by opi** [comment]
rejecting this PR as : 

- upgrading bootstrap should be a separate PR
- installing bootstrap-toggle should be done with gulp
- modifing comment style is out of scope ;)
- unmaintained work for more than a year

thanks anyway, Ill be glad to help you bring this PR back to life

**Comment by e-lie** [comment]
Will try to revive this for the Brique Camp :-)

**Pull request closed without merging**
