### PR TITLE
Fixed typo (missing 'r' in "configuré")

### PR DESCRIPTION
**Pull request by nicofrand**

### CODE REVIEW

**Comment by alexAubin** [comment]
Merging this as a microdecision.

Thanks for the pull request /

**Comment by opi** [comment]
we should NEVER edit translation files outside of weblate. Please edit French (and other languages) on https://translate.yunohost.org

**Comment by nicofrand** [comment]
Oh sorry. You can revert it if you want, I'll update it on translate.yunohost.org.

**Comment by opi** [comment]
btw, everything went fine when update translate.ynh, sorry for my angry comment, and thanks for fixing translation !

**Comment by nicofrand** [comment]
Really not an issue. I am discovering Yunohost environment and I am still confused/lost most of the time, you pointed me to the right direction.

Le 14 févr. 2017 10:06 PM, opi <notifications@github.com> a écrit :

btw, everything went fine when update translate.ynh, sorry for my angry comment, and thanks for fixing translation !

**Pull request merged**
