### PR TITLE
Replace pacman with nyancat 8)

### PR DESCRIPTION
**Pull request by alexAubin**
:nerd_face:  ¯\\\_(ツ)\_/¯

Pros: It can make people even moar happy about using YunoHost admin
Cons: It can make people even moar angry about using YunoHost admin

:thinking:

### CODE REVIEW

**Comment by zamentur** [comment]
https://www.dailymotion.com/video/x1ivtx

**Comment by zamentur** [comment]
What should we do with this PR ?

**Comment by alexAubin** [comment]
Sooo maybe as a more acceptable solution, now it's triggered by the famous Konami code

Easter is coming ;P

**Comment by alexAubin** [comment]
Drunky mergin' guyz

**Pull request merged**
