### PR TITLE
Add upstream manifest info (install, configuration pages)

### PR DESCRIPTION
**Pull request by g1smo**

### CODE REVIEW

**Review by Tagadda — APPROVED** [review]
LGTM ! :rocket:

**Comment by tituspijean** [comment]
It looks like it is being partially superseded by #486, do you concur @Axolotle? (License info would be missing though)

**Comment by Axolotle** [comment]
> It looks like it is being partially superseded by #486, do you concur @Axolotle? (License info would be missing though)

Indeed, #486 will address all the app manifest V2 changes. #428 will also be superseded.
I'm adding `license` and `userdoc` which was also missing, thx!

**Comment by alexAubin** [comment]
Superseded by https://github.com/YunoHost/yunohost-admin/pull/486

**Pull request closed without merging**
