### PR TITLE
Add noscript tag

### PR DESCRIPTION
**Pull request by dattaz**
add noscript tag, to say activate javascript when javascript is deactivate 
No data-y18n because localisation doesn't work without javascript

inspiration come from https://twitter.com/brabram/status/784463217821097984

### CODE REVIEW

**Comment by zamentur** [comment]
Seems good for me :)

**Comment by opi** [comment]
Nice enhancement! Maybe you can add a `warning` or `error` wrapper (through bootstrap classes), and write a message like "You must enable Javascript to view this page properly."

**Comment by dattaz** [comment]
Done, with warning wrapper 
screen shot 2016-10-09 at 21 33 07

**Comment by opi** [comment]
Thanks !

**Comment by M5oul** [comment]
It's not well displayed on my side:

capture du 2016-10-10 10-23-42

**Comment by M5oul** [comment]
- Adding solved the issue:
```diff
            </div>
+            <br/>
+            <br/>
            <noscript>
```

It seems there is a `div` issue `loading…` is displayed on `noscript` balises.

- We could also hide `loading…` as it's non sense without JavaScript.
This solution also solved the display.

**Comment by opi** [comment]
Warning position fixed with 4f28ba44268de77527c7ae280b876ade4ca529b9

**Comment by opi** [comment]
BTW, hidding/displaying content depending on Javascript possibility should be handle more properly with `js`/`no-js` class on `<body>` tag, like Modernizer framwork does.

**Pull request merged**
