### PR TITLE
Reboot function in the admin/tools menu

### PR DESCRIPTION
**Pull request by polytan02**
Reboot function (to be done !), to add the possibility of remotely rebooting the yunohost system.

The function added is JUST AN EXAMPLE and needs to be done properly.

### CODE REVIEW

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/yunohost/pull/190

**Comment by polytan02** [comment]
This was an old request, which would need to be re-evaluated.
I closed it because the previous tem position was that "iff the system gets hack, the attacker could shut down your server easily" but it has been requested to reopen it.

I will let the community to decide ! :)

**Comment by bochecha** [comment]
> I will let the community to decide ! :)

As a data point in favour of this, I find myself locked out of my home network right now, because for some reason Yunohost doesn't provide the Wi-Fi hotspot any more. As a result I can't connect to it through SSH, which means I can't reboot it.

However I do have access to the admin UI from the outside.

Having a way to reboot it from the admin tools UI seems like a no brainer to me: in some situations it is the only way to reboot the box.

**Comment by opi** [comment]
Work is done here https://github.com/YunoHost/yunohost-admin/pull/173 , any review is welcome.

**Pull request closed without merging**
