### PR TITLE
Add support for featured community apps

### PR DESCRIPTION
**Pull request by maniackcrudelis**
Add support for featured apps (https://forum.yunohost.org/t/about-community-and-official-apps/6372)
For now, it shows a star for each apps marked as Featured in the community list ("featured": true).

I know we discussed about having a tag merging "Featured" and "Unmaintained", but that's actually the first time I work with php and JS ! So I need time to figure that out...

~Also, I "tried" to add a filter for featured and official apps. The filter is in the list on the app list. But the filter itself doesn't work for the moment. I don't know why. I really could use some help on that part !~

This PR is related to https://github.com/YunoHost/apps/pull/677 for the list itself.

**This PR should be merged after https://github.com/YunoHost/doc/pull/927**

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Ok I give up the idea of making this filter works. I don't know how this is supposed to work, and there's not enough comment in that part of the code to have any idea how it's supposed to works.

**Comment by maniackcrudelis** [comment]
Made some change on this PR, following https://github.com/YunoHost/apps/pull/677.

- Added support for High Quality apps
- Restrict this flag only for app with a level at 8 or more.
- Modify Featured apps to be only those with the flag `featured`. And restrict it only to app with already the flag `high_quality`
- Change from a text with a icon to a label.
- Finally make the filter works, for High Quality only or Featured only.

**Comment by maniackcrudelis** [comment]
Now we have also a support of 3 different states for an unmaintained app.

- 'orphaned'. For unmaintained apps.
- 'request_help'. For packagers wanted help for an app.
- 'request_adoption'. For an app which is going to be unmaintained.



Also, I removed the logo to replace it by a colored label. To be more visible.
I had also kept the name of the maintainer, is there's one in the manifest, aside of the label.

**Comment by kay0u** [comment]
Maybe the "Featured" keyword shouldn't be in red, because in this whole area, red is a bad thing (level 0, orphaned...). What do you think?

**Comment by maniackcrudelis** [comment]
I used red for 2 reasons.

- First, there's not so much colors in the css used for those labels :wink:
- And, I wanted a color that users would notice.

But it could be of any other color.

**Comment by maniackcrudelis** [comment]
Ready for reviews

**Comment by maniackcrudelis** [comment]
This PR is the next on the list of https://github.com/YunoHost/apps/pull/677
So its waiting for your love :)

I'll have a look this weekend to the same page in the doc to see if I can update it as well.

**Comment by maniackcrudelis** [comment]
> I'll have a look this weekend to the same page in the doc to see if I can update it as well.

https://github.com/YunoHost/doc/pull/960 ...

**Comment by alexAubin** [comment]
Uh but I don't understand how this PR is blocking the other PRs ? To me this PR is the least urgent as it can be done anytime we want, but first we should do the whole migration to apps.json ?

**Comment by maniackcrudelis** [comment]
This PR isn't blocking anything, but it seems logic to have a support of those 2 tags before starting to use them.
The documentation itself is another problem.
The idea of this order is to avoid merging PR managing something not already done on another side of the code. This order isn't mandatory, just more logical for me.

**Comment by alexAubin** [comment]
Hmokay but to me there are still many design decision to take before merging this ... we evoked a few of  those during the meeting two weeks ago if I remember correctly
- official / community tags won't make much sense anymore with the new unified apps.json + high quality, so those are to be removed
- to me the 'featured' thing shouldn't be handled as just "yet-another-badge" but instead something like a special app category, so e.g. put on top of the app list or something like this (ideally if we had the app category system it could be the default filter or something) ... and yet we agreed that for now the featured app are still kinda in stand by so it's not clear whether we should integrate it in the admin for now or not ...
- misc css tweaks, and also I'm thinking we should add some info-bubbles when hovering the maintenance status to explain people what it means to be in "request for adoption" and encourage them contributing

I can / will work on this at some point but the bottom line is that it'll take at least a few days and in the meantime nothing really prevents to move forward on the other PRs @.@

**Comment by maniackcrudelis** [comment]
> official / community tags won't make much sense anymore with the new unified apps.json + high quality, so those are to be removed

Official and community will be still relevant until we removed them definitively. Which is for ynh 4.x +6 months for the last discussion.

> to me the 'featured' thing shouldn't be handled as just "yet-another-badge" but instead something like a special app category, so e.g. put on top of the app list or something like this (ideally if we had the app category system it could be the default filter or something) ... and yet we agreed that for now the featured app are still kinda in stand by so it's not clear whether we should integrate it in the admin for now or not ...

Kind of stand by because we don't know yet how to promote apps to this status. But for me, it was already clear that we want to keep the idea.
Considering how to handle the "tag" or whatever it would be, it doesn't looks like a big deal if we want to change it later.
I think the existing filter could be used to sort the app in the app list. I agree indeed to put those apps in first position.

> misc css tweaks, and also I'm thinking we should add some info-bubbles when hovering the maintenance status to explain people what it means to be in "request for adoption" and encourage them contributing

I don't remember we have talked about that, but yes could be nice.
Don't think though we have to that in the first place.

Anyway, waiting or not doesn't really matters to me. If, we're sure we're going to do those modifications soon.
Otherwise, this whole idea would have no meaning. If the final user don't see the badges, it's useless...

**Comment by maniackcrudelis** [comment]
So, what do we do ?
Do you want to rework this PR before merging it ?
Should we go for https://github.com/YunoHost/apps/pull/727 and followings and keep that PR for later ?

**Comment by Psycojoker** [comment]
If I understand correctly, since #242 is merged this PR is not relevant anymore, so I'm closing it. Don't hesitate to complain if I've made a mistake :sweat_smile:

**Pull request closed without merging**
