### PR TITLE
[enh][love] Create CONTRIBUTORS.txt file.

### PR DESCRIPTION
**Pull request by opi**

### CODE REVIEW

**Comment by Jibec** [comment]
hi there. Weblate can generate such things for translators. I think you should write only manually add source-code contributor to this file, and then add translator in a big copy/paste. Here is the result for "yunohost-admin" (we can do the same of other sub-projects):

* Dutch

    * DUBWiSE <accounts@maartenderks.nl>
    * dosch <git@dosch.nl>
    * Jérôme Lebleu <jerome@yunohost.org>
    * opi <opi@zeropi.net>


* English

    * Bugsbane <user581@xymail.info>


* French

    * Étienne Deparis <etienne@depar.is>
    * Jean-Baptiste <jean-baptiste@holcroft.fr>
    * Jérôme Lebleu <jerome@yunohost.org>
    * opi <opi@zeropi.net>
    * Zamentur aka ljf <valentin@grimaud.me>


* German

    *  <david.bartke@web.de>
    * Felix Bartels <felix@host-consultants.de>
    * Jérôme Lebleu <jerome@yunohost.org>
    * opi <opi@zeropi.net>


* Hindi

    * Anmol <github@datamol.in>


* Italian

    *  <github@danneso.eu.org>
    * Jérôme Lebleu <jerome@yunohost.org>
    * opi <opi@zeropi.net>
    * Thomas Bille <thomas.bille625@gmail.com>
    * Vincent <vincent.manillier@openmailbox.org>


* Portuguese

    * Deleted User <noreply@weblate.org>


* Spanish

    * Jérôme Lebleu <jerome@yunohost.org>
    * Juanu <juanu.sandoval@gmail.com>
    * opi <opi@zeropi.net>


* Turkish

    * Jérôme Lebleu <jerome@yunohost.org>

**Comment by julienmalik** [comment]
Except initiating the translation with an empty/english file, I doubt Jerome & opi worked on the dutch/turkish/german(/spanish?) translation, but I might be wrong of course :)

**Comment by opi** [comment]
@julienmalik you're right !

@Jibec nice, I'll update the CONTRIBUTORS.txt file then. Can you explain who you get this list please ?

**Comment by opi** [comment]
Split contrib and translators in 1f655392ea3d1967f23e5d790cc41f45a51c88a5 ; I'm not a big fan of this distinction though

**Comment by M5oul** [comment]
Why not using a markdown file format?

**Comment by M5oul** [comment]
All this commits could be stashed on one commit before merging.

**Pull request merged**
