### PR TITLE
Avoid suggesting saved password on user password change form

### PR DESCRIPTION
**Pull request by JocelynDelalande**

### CODE REVIEW

**Review by alexAubin — APPROVED** [review]
Okay I guess but I have no idea how that stuff works haha

@Axolotle do you have any opinion on this ?

**Comment by Axolotle** [comment]
Hey, didn't know about this either. Tested it but i don't have any password suggestion or something to remember a new one. I guess i have something blocking this.
But we should consider to do it for every password creation i guess, in app install forms for example ?

And this prop won't be passed to the component since i forgot to add `v-bind="$attrs` to its definition, WHOOPSIES.

**Comment by andretheolauret** [comment]
@alexAubin This PR is supposed to modify the HTML attribute so that the browser does not offer already saved passwords

Tested it on my development environment it works like a charm, tested with Deepin-Browser(Chromium), chromium suggest nothing and tested on iPhone (Safari), doesn't show already registered password, I think it's fine 

This PR should be merged please , after six month lol x)

**Comment by alexAubin** [comment]
Alrighty it wasn't clear from Axolotle's comment ... thanks for the testing and bump :+1:

**Pull request merged**
